### ISSUE TITLE
Development of an Gpx/KML To GeoJson Konverter

### ISSUE THREAD

**Issue by RudiThoeni** [noi-techpark/odh-api-core#333]
Functionality:

-Add a Route that konverts a KML/GPX File and returns as GeoJSON Data
-Route where it is possible to pass an URL 
-Route where it is possible to post a file

Please estimate the effort.

After the prototype works inside the api, lets discuss about deploying it as microservice

**Comment by toburger** [comment]
My estimate for the effort providing the endpoints inside the API project is a dozen hours, maybe less.

**Comment by RudiThoeni** [comment]
ok thx, perfect

**Comment by RudiThoeni** [comment]
Hi @toburger 

I tested with kml files it works ;) very good....
lets add also the gpx file support

v1/GeoConverter/GpxToGeoJson

same strategy as on kml files
