### ISSUE TITLE
Searchfilter strange behaviour in NL, CS, PL, FR, RU

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/odh-api-core#342]
It seems that there is a bug in the searchfilter functionality in languages mentioned in the title.

I put an example of search I did and Where I got strange response.

By doing the query in German I get 6 results all containing the "mousse" word in the title. See link below:
https://tourism.opendatahub.bz.it/v1/Article?pagesize=25&pagenumber=1&language=de&searchfilter=mousse

By doing the query in Italian I get 5 results all containing the "mousse" word in the title. See link below:
https://tourism.opendatahub.bz.it/v1/Article?pagesize=25&pagenumber=1&language=it&searchfilter=mousse

By doing the query in English I get 7 results all containing the "mousse" word in the title. See link below:
https://tourism.opendatahub.bz.it/v1/Article?pagesize=25&pagenumber=1&language=en&searchfilter=mousse

By doing the query in all other languages I get always 992 results (I think it means all records). See the NL query below as example:
https://tourism.opendatahub.bz.it/v1/Article?pagesize=25&pagenumber=1&language=nl&searchfilter=mousse

**Comment by RudiThoeni** [comment]
fixed
