### ISSUE TITLE
As an Open Data Hub manager I want to upload through the Metadata API an image for each dataset, to improve the rendering on the website.

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/odh-api-core#365]
The Image will be uploaded through the new Data Browser and stored. Each image should have at least the following fields:
- URL
- Copyright
- License

The goal is to reuse the file uploader component already developed in the Data Browser.

**Comment by RudiThoeni** [comment]
Hi Stefano
I added the well known ImageGallery Object List to the Metadata Data model
<img width="308" alt="image" src="https://github.com/noi-techpark/odh-api-core/assets/30471361/55408f65-6e32-46ed-917b-e48a1a0ffc03">

so now it should be easily reused the ImageGallery Component in the Databrowser

**Comment by sseppi** [comment]
@ila131 and @d3liaa can you please add the Gallery Component configuration of this new field of the MetaData API on the DEtail and Edit view?

**Comment by sseppi** [comment]
@d3liaa can you please test this feature and let me know if everythin is fine?

**Comment by d3liaa** [comment]
Everything works as it should :) 
Q: Is it correct that the image is not displayed in the list view ?

**Comment by sseppi** [comment]
@d3liaa Thank you for testing and letting us know!

For the images in the list view, we will discuss it and let you know.

**Comment by RudiThoeni** [comment]
Hi @d3liaa 

> Q: Is it correct that the image is not displayed in the list view ?

You mean that the property `ImageGallery` is not in the json output?
On next time you edit/save a metadata object it should be populated

**Comment by RudiThoeni** [comment]
now i have seen there is always 
`"ImageGallery": null,
`
in each record
means no ImageGallery is set.....

did you test to upload an image and save the object?

**Comment by RudiThoeni** [comment]
I tested and it worked
https://api.tourism.testingmachine.eu/v1/MetaData/751dc9ad-5fd9-4b48-b98d-6702f5be57a9
`"ImageGallery": [
{
"Width": null,
"Height": null,
"License": null,
"ValidTo": null,
"ImageUrl": "https://images.tourism.testingmachine.eu/api/Image/GetImage?imageurl=958f3591-3650-4e95-b04e-7a737af152d0.png",
"CopyRight": null,
"ImageDesc": {},
"ImageName": null,
"ImageTags": null,
"ValidFrom": null,
"ImageTitle": {},
"ImageSource": null,
"IsInGallery": null,
"ImageAltText": {},
"ListPosition": null,
"LicenseHolder": null
}
],
"SingleDataset": true,
"ApiDescription": {
"en": "This dataset exposes all events taking place at NOI Techpark"
}`

**Comment by d3liaa** [comment]
@RudiThoeni : no, sorry maybe i was not clear. I just asked if the image should be visible in the table view. It was a pure configuration and design question.
