### ISSUE TITLE
As an opendatahub developer i want to have a distinct function in the rawfilter

### ISSUE THREAD

**Issue by RudiThoeni** [noi-techpark/odh-api-core#371]
referring to https://github.com/noi-techpark/it.bz.opendatahub.databrowser/issues/416

Not sure if this is easily possible

**Comment by RudiThoeni** [comment]
added a new generic Endpoint for this operation since it was not easy to integrate in the rawfilter.......
documented here https://github.com/noi-techpark/odh-docs/wiki/Distinct-Search-in-ODH-Tourism-api

**Comment by toburger** [comment]
The following pull requests implements the naive approach which results in the wrong data when extracting multiple fields: #375

#### My question:

Is it common to query for the cross product of multiple fields or should we restrict the endpoint to query for a single field?
