### ISSUE TITLE
Performance Test HGV / LTS / ODH Interfaces

### ISSUE THREAD

**Issue by RudiThoeni** [noi-techpark/odh-api-core#382]
Check the Response Times on the LTS, HGV and ODH Interfaces with different combinations

LTS: https://lcs.lts.it/api/data.svc/xml/AccommodationDataSearch  (POST)
HGV: http://www.easymailing.eu/mss/mss_service.php (POST)
ODH: https://tourism.api.opendatahub.com/v1/AccommodationAvailable?boardfilter=0&arrival=2023-11-11&departure=2023-11-12&roominfo=0-18,18&source=sinfo&detail=1&bokfilter=hgv&availabilityonly=true&withoutids=false (POST)

Note that HGV + ODH offers the possibility to not send any Hotel Ids, so the cache is used.....

I tested 
Partschins 98 Accommodations
Meran 2185 Accommodations
South Tyrol 10100 Accommodations

3 Tests where made for each request

**Comment by RudiThoeni** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/R8BD6~1.THO/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/R8BD6~1.THO/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



  | LTS (direkt) | HGV (direkt) | OHD(HGV) | ODH(LTS) | ODH(kombiniert LTS+HGV) (merge)
-- | -- | -- | -- | -- | --
Partschins (107) | 0.2 / 0.1 / 0.1 | 0.3 / 0.3 / 0.2 | 0.4 / 0.4 / 0.4 | 0.7 / 0.3 / 0.3 | 0.7 / 0.6 / 0.7
Meraner Land (2155) | 2.4 / 1.9 / 2.2 | 1.8 / 1.4 / 1.4 | 2.1 / 1.8 / 1.9 | 2.4 / 2.7 / 2.5 | 4.9 / 4.1 / 4.3
Südtirol (10111) |   | 2.5 / 0.9 / 1.0 | 3 / 1.3 / 1.4 | 9.6 / 8.9 / 8.7 | 10.3 / 9.8 / 10.5
with ids passed | 8.9 / 7.9 /9.2 | 3.8 / 3.8 / 3.6 | 4.5 / 4.1 / 4.2 | 8.8 / 9.1 / 11 | 14.4 / 17 / 14



</body>

</html>

**Comment by RudiThoeni** [comment]
Conclusion:

- On small lists the LTS Service is the fastest but it is not performing constantly (example 0.1 - 0.1 - 0.4 .....) so this tests are 
- HGV offers the possibility to do an availability request without passing Ids, if done the caching system of HGV is used....
- The ODH merging requires some time could surely be improved.
- Performance loss between direct LTS call and ODH call is very low .....

**Comment by niettadesantis** [comment]
Thank you Rudi, if needed I will come up to you again!
