### ISSUE TITLE
As an opendatahub developer i want to examine mismatches between the Booking information provided by HGV and LTS

### ISSUE THREAD

**Issue by RudiThoeni** [noi-techpark/odh-api-core#402]
Some tests todo

List of Accommodations which have isBookable set to true and no HGV Information

List of Accommodations which have isBookable set to false and HGV Bookable set to true

List of Accommodatiosn which have isBookable set to true and HGV Bookable set to false

**Comment by RudiThoeni** [comment]
> Some tests todo
> 
> List of Accommodations which have isBookable set to true and no HGV Information

https://tourism.api.opendatahub.com/v1/Accommodation?rawfilter=and(isnull(AccoHGVInfo),eq(IsBookable,true),eq(SmgActive,true))&fields=AccoHGVInfo,IsBookable,AccoBookingChannel,LastChange,_Meta.LastUpdate,SmgActive,Active,HgvId,Shortname

Strange case to verify

Hotel My Arbor
LTS ID: 1A92BA676ABD62E433DEAFFD0EB2E08E
HGVID:12839
present on Booking Suedtirol
https://www.bookingsuedtiro.com/de/suche?query=Hotel+My+Arbor&propertyId=12839
https://www.bookingsuedtirol.com/de/brixen/hotel-my-arbor
LTS POS Info returns
```
	<HotelPOS>
		<Head A0RID="1A92BA676ABD62E433DEAFFD0EB2E08E">
			<Data POS1ID="998" POS2LTSPrim="0" POS2HotelRID="12839" POS1Des="www.bookingsuedtirol.com - in Aktivierungsphase"/>
		</Head>
	</HotelPOS>
```
HGV Interface returns
```
     <id>12839</id>
      <id_lts>1A92BA676ABD62E433DEAFFD0EB2E08E</id_lts>
      <bookable>0</bookable>
      <name>Hotel My Arbor</name>
      <type>1</type>
      <stars>4.5</stars>
      <language>de</language>
      <price_engine>0</price_engine>
      <price_from>150</price_from>
      <available_from>2024-01-11</available_from>
```

Apartments Chalet Milé
LTS ID: 91340288E8D4FDF9FDDE3961CE09F276
HGVID:13519
present on Booking Suedtirol
https://www.bookingsuedtirol.com/de/suche?query=Apartments+Chalet+Mil%C3%A9&propertyId=13519
https://www.bookingsuedtirol.com/de/stulrichingroedenortiseivalgardena/apartments-chalet-mile
LTS POS Info returns
```
	<HotelPOS>
		<Head A0RID="91340288E8D4FDF9FDDE3961CE09F276">
			<Data POS1ID="998" POS2LTSPrim="0" POS2HotelRID="13519" POS1Des="www.bookingsuedtirol.com - in Aktivierungsphase"/>
		</Head>
	</HotelPOS>
```
HGV Interface returns no data

should be the same?

**Comment by RudiThoeni** [comment]
another case to investigate

824D85ED29E711D599D20050DA7125DB

LTS gives

<HotelPOS>

<Head A0RID="824D85ED29E711D599D20050DA7125DB">

<Data POS1ID="2" POS2LTSPrim="0" POS2HotelRID="10984" POS1Des="www.bookingsuedtirol.com<http://www.bookingsuedtirol.com/>"/>

</Head>

</HotelPOS>

HGV Interface does not find this ID (neither 824D85ED29E711D599D20050DA7125DB, or 10984)

The strange thing is that on booking suedtirol this accommodation exists see the Id in the url......(https://www.bookingsuedtirol.com/de/suche?query=Gran+Tubla&propertyId=10984)

**Comment by RudiThoeni** [comment]
Status: waiting answer from HGV

**Comment by RudiThoeni** [comment]
Got Feedback from HGV that this is a special case:

> Habe vom Kunden einen spezielle Anforderung erhalten.
> 
> Hierzu folgende Notiz vom März 2023:
> 
> hat angerufen wegen einer Stornierung xxxxxx, habe ich so im Logbook hinterlegt. Möchte außerdem bei keinem Portal mehr buchbar sein bis auf Booking Südtirol und dem Tourismusverein. Habe Quellen deaktiviert. 
> 
> So wie es aussieht, müsste dieser Kunde nun auch beim LTS deaktiviert werden.
> 
> Soweit ich mich erinnere, kann im LTS aber nur die Buchbarkeit von ALLEN Portale deaktivieren werden, oder von keinem.
> 
> Die Buchbarkeit wird mit der Quelle Portal = Booking Südtirol gemacht, wo dieser Betrieb aufscheint und für mich ist dort das Problem.
> 
> In unserem System ist dieser Kunde eurer Quelle “suedtirol.info” nicht zugweisen


Ok so lets agree on the workflow that on every data where 
AccoHGVInfo = null
OR
AccoHGVInfo.Bookable = false
The Accommodation is not bookable
So this special cases are covered, and also the case when an Accommodation is in this activation phase

cheers
Rudi

**Comment by RudiThoeni** [comment]
added also a sync that clears the accohgvinfo in case the association is removed
https://issues.opendatahub.com/Ticket/Display.html?id=14923

**Comment by antoniettadesantis** [comment]
Perfect, thank you Rudi.
