### ISSUE TITLE
As a developer i want to have the weatherforecasts per municipality integrated into the Tourism Api

### ISSUE THREAD

**Issue by RudiThoeni** [noi-techpark/odh-api-core#406]
https://mobility.api.opendatahub.com/v2/flat,node/WeatherForecast/*/latest

The idea is to retrieve the forecasts per municipality

**Comment by RudiThoeni** [comment]
using the file on s3
added a PR, wip
https://github.com/noi-techpark/odh-api-core/pull/409

**Comment by RudiThoeni** [comment]
https://api.tourism.testingmachine.eu/v1/Weather/Forecast

**Comment by RudiThoeni** [comment]
@rcavaliere  i deployed everything on testing https://api.tourism.testingmachine.eu/v1/Weather/Forecast
i take the data from the file on S3 and parse it to the tourism format..... please check and if this is ok i will deploy on prod so STA can use it.....

**Comment by rcavaliere** [comment]
@RudiThoeni thanks a lot! Can you tell me which are the existing other API calls for the weather forecasts at regional and "bezirks" level?

**Comment by RudiThoeni** [comment]
https://tourism.api.opendatahub.com/v1/Weather
https://tourism.api.opendatahub.com/v1/Weather/District
https://tourism.api.opendatahub.com/v1/Weather/Realtime

https://tourism.api.opendatahub.com/v1/Weather/Forecast (only working on test prod deployment has to be done https://api.tourism.testingmachine.eu/v1/Weather/Forecast)

**Comment by RudiThoeni** [comment]
all described in swagger
https://tourism.api.opendatahub.com/swagger/index.html#/Weather

**Comment by rcavaliere** [comment]
Positive feedback here, I think we can put on production, @RudiThoeni 
@ohnewein @sseppi we have a wonderful use case here with STA, with weather predictions visualized dynamically on the internal monitors based on the municipality in which the train is stopping.

**Comment by RudiThoeni** [comment]
ok all on production
