### ISSUE TITLE
As a NOI News and NOI Events editor, I want to add link to videos to my Events and News

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/odh-api-core#439]
The communication asked to have the possibility to add the link to videos related to the news or events they are editing.

They will input the link to videos uploaded on known platforms like for example Youtube or Vimeo.

A possible solution could be, create a "VideoGallery" that conatins a list of video with the following infromation:
- title
- link
- license
- ...

**Comment by RudiThoeni** [comment]
Hi Stefano

We have the Object `VideoItems` already in the Datamodel for Activities & Pois i could reuse this on the EventShort data.
It has all requested fields and also more..... 

Example:
`"VideoItems": {
        "de": [
            {
                "Name": "00527C33B94A42C2BABE4658EF211A15",
                "Url": "<iframe width=\"1280\" height=\"720\" src=\"//www.youtube.com/embed/blabla?list=UUqSmyuqVNwklKKlqqdMmV_A\" frameborder=\"0\" allowfullscreen=\"\"/>",
                "VideoSource": "Youtube",
                "VideoType": "Werbefilm",
                "StreamingSource": "http://www.youtube.com/embed/blabla",
                "VideoTitle": "",
                "VideoDesc": "Video Beschreibung DE",
                "Active": true,
                "CopyRight": "Corvara",
                "License": "LTS",
                "LicenseHolder": null,
                "Language": "de"
            }
        ],
        "it": [
            {
                "Name": "00527C33B94A42C2BABE4658EF211A15",
                "Url": "<iframe width=\"960\" height=\"720\" src=\"//www.youtube.com/embed/blabla\" frameborder=\"0\" allowfullscreen=\"\"/>",
                "VideoSource": "Youtube",
                "VideoType": "Film pubblicitario",
                "StreamingSource": "http://www.youtube.com/embed/zUUwX5LuyB0?list=blabla",
                "VideoTitle": "",
                "VideoDesc": "Video Beschreibung it",
                "Active": true,
                "CopyRight": "Corvara",
                "License": "LTS",
                "LicenseHolder": null,
                "Language": "it"
            }
        ],
        "en": [
            {
                "Name": "00527C33B94A42C2BABE4658EF211A15",
                "Url": "<iframe width=\"1280\" height=\"720\" src=\"//www.youtube.com/embed/blabla\" frameborder=\"0\" allowfullscreen=\"\"/>",
                "VideoSource": "Youtube",
                "VideoType": "Promotional",
                "StreamingSource": "http://www.youtube.com/embed/blabla",
                "VideoTitle": "",
                "VideoDesc": "Video Beschreibung EN",
                "Active": true,
                "CopyRight": "Corvara",
                "License": "LTS",
                "LicenseHolder": null,
                "Language": "en"
            }
        ]
    },`

However currently we don't have the component in the Databrowser, it is a Dictionary (language based) and not a simple list so not so straightforward/easy to implement.........i think we could ask Christian Gapp to implement it?

**Comment by sseppi** [comment]
@RudiThoeni I agree! We need the same Object also in the Articles for the NOI News.

**Comment by RudiThoeni** [comment]
VideoItems visible on Testing, added to
ODHActivityPoi
Article (News)
Events NOI

**Comment by RudiThoeni** [comment]
done, all we have to do is bring the actual databrowser on testing to production
