### ISSUE TITLE
As a developer i want to test the performance between the new (json) and old (xml) availability search interface

### ISSUE THREAD

**Issue by RudiThoeni** [noi-techpark/odh-api-core#477]
Goal is to check if the caching feature of the new interface is it worth to change

**Comment by RudiThoeni** [comment]
I did some performance tests

With heavy requests over whole south tyrol (by not passing any Ids

```
LCS interface (xml)

1506 results (216KB) Response size
6.5s
491ms
503ms

1792 results (290KB) Response size
8.17s
1100ms
680ms
```

```
Json Interface 

1454 results (1.6MB) 
6.54s
1200ms
1200ms
1900ms

1775 results (2.23MB)

10.44s 
1552ms
1620ms
```

The slight difference in the results is to check........

For the performace differences this could be also because of the response size........
xml
![image](https://github.com/user-attachments/assets/b7991e24-da0d-47e7-81a6-744494d24d50)
json
![image](https://github.com/user-attachments/assets/9ef2e50a-2954-493f-8519-849a9e13961e)
The new interface seems to not use compression

more infos to come

**Comment by RudiThoeni** [comment]
@niettadesantis  here is the issue for some performance testing between new / old LTS interface

**Comment by antoniettadesantis** [comment]
Hi @RudiThoeni, 
thank you for your tests. It's very important that we keep an eye on it as we want to integrate the check of availability of all accommodations on suedtirol.info in January and of course we have a UX solution for long loading times (searches in whole South Tyrol or in big regions) but the bad performance of the api could have a bad impact in the Core Web Vitals Indicators of Google and be negative for the ranking in the Search Engines. 
So please if you identify performance issues, write directly to LTS and put me and Michael in CC. Thank you very much!
